/* ---------------------------------------------------------------------------------------------------------
  PROYECTO      : CAR_CENTER_PROJECT
  FECHA CREACION: 24 de MARZO de 2021
  DESCRIPCION   : Creacion de las tablas del modelo 
  AUTOR         : Marielena Barrios Reinoso
--------------------------------------------------------------------------------------------------------- */
  --ELIMINAR TABLAS
  /*
    DROP TABLE FACTURA CASCADE CONSTRAINTS;
    DROP TABLE DESCRIPCION_SERVICIO CASCADE CONSTRAINTS;
    DROP TABLE VEHICULO CASCADE CONSTRAINTS;
    DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
    DROP TABLE ALMACEN CASCADE CONSTRAINTS;
    DROP TABLE MECANICO_RESPONSABLE CASCADE CONSTRAINTS;
    DROP TABLE CLIENTE CASCADE CONSTRAINTS;
  */
  -- TABLA CLIENTE
  CREATE TABLE CLIENTE(
    NUM_IDENT_CLI VARCHAR2(20),
    TIPO_IDENT_CLI VARCHAR2(20),
    PRIMER_NOMBRE VARCHAR2(50),
    SEGUNDO_NOMBRE VARCHAR2(50),
    PRIMER_APELLIDO VARCHAR2(50),
    SEGUNDO_APELLIDO VARCHAR2(50),
    NUMERO_CONTACTO NUMBER,
    DIRECCION VARCHAR2(100),
    CORREO_ELECTRONICO VARCHAR2(100)
    );
  ALTER TABLE CLIENTE ADD CONSTRAINT PK_NUM_IDENT_CLI PRIMARY KEY (NUM_IDENT_CLI);      
  
  -- TABLA MECANICO_RESPONSABLE
  CREATE TABLE MECANICO_RESPONSABLE(
    NUM_IDENT_MEC VARCHAR2(20),
    TIPO_IDENT_MEC VARCHAR2(20),
    PRIMER_NOMBRE VARCHAR2(50),
    SEGUNDO_NOMBRE VARCHAR2(50),
    PRIMER_APELLIDO VARCHAR2(50),
    SEGUNDO_APELLIDO VARCHAR2(50),
    NUMERO_CONTACTO NUMBER,
    DIRECCION VARCHAR2(100),
    CORREO_ELECTRONICO VARCHAR2(100),
    ESTADO_MECANICO_RESP VARCHAR2(20)
    );
  ALTER TABLE MECANICO_RESPONSABLE ADD CONSTRAINT PK_NUM_IDENT_MEC PRIMARY KEY (NUM_IDENT_MEC);      
    
  -- TABLA ALMACEN
  CREATE TABLE ALMACEN(
    COD_SUCURSAL NUMBER,
    NOMBRE_ALMACEN VARCHAR2(50),
    DIRECCION VARCHAR2(100),
    TELEFONO_CONTACTO NUMBER,
    CIUDAD VARCHAR2(50)
    );
  ALTER TABLE ALMACEN ADD CONSTRAINT PK_COD_SUCURSAL PRIMARY KEY (COD_SUCURSAL);
  CREATE SEQUENCE SEQ_ALMACEN MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
  
  -- TABLA PRODUCTO
  CREATE TABLE PRODUCTO(
    COD_PRODUCTO NUMBER,
    NOMBRE_PRODUCTO VARCHAR2(50),
    VALOR_UNITARIO NUMBER,
    CANTIDAD_PROD NUMBER,
    DESCUENTO NUMBER
  );
  ALTER TABLE PRODUCTO ADD CONSTRAINT PK_COD_PRODUCTO PRIMARY KEY (COD_PRODUCTO);      
  CREATE SEQUENCE SEQ_PRODUCTO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
  
  CREATE TABLE VEHICULO(
    COD_VEHICULO NUMBER,
    NOMBRE VARCHAR2(50),
    MODELO VARCHAR2(50),
    MARCA VARCHAR2(50)
  );
  ALTER TABLE VEHICULO ADD CONSTRAINT PK_COD_VEHICULO PRIMARY KEY (COD_VEHICULO);      
  CREATE SEQUENCE SEQ_VEHICULO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
  
  
  CREATE TABLE DESCRIPCION_SERVICIO(
    COD_SERVICIO NUMBER,
    VALOR_MANO_OBRA NUMBER,
    DESCUENTO NUMBER,
    OBSERVACION VARCHAR2(1500),
    COD_PRODUCTO NUMBER,
    NUM_IDENT_MEC VARCHAR2(20),
    CAN_PRODUCTO_VENDIDO NUMBER
  );
  ALTER TABLE DESCRIPCION_SERVICIO ADD CONSTRAINT PK_COD_SERVICIO PRIMARY KEY (COD_SERVICIO);
  ALTER TABLE DESCRIPCION_SERVICIO ADD CONSTRAINT FK_COD_PRODUCTO FOREIGN KEY(COD_PRODUCTO) REFERENCES PRODUCTO (COD_PRODUCTO);
  ALTER TABLE DESCRIPCION_SERVICIO ADD CONSTRAINT FK_NUM_IDENT_MEC FOREIGN KEY(NUM_IDENT_MEC) REFERENCES MECANICO_RESPONSABLE (NUM_IDENT_MEC);      
  CREATE SEQUENCE SEQ_DESCRIPCION_SERVICIO MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;
  
  
  CREATE TABLE FACTURA(
    NUM_FACTURA NUMBER,
    FECHA_FACTURA DATE,
    PLACA VARCHAR2(50),
    FORMA_PAGO VARCHAR2(50),
    MEDIO_PAGO VARCHAR2(50),
    IVA NUMBER,
    VALOR_TOTAL_FACT NUMBER,
    NUM_IDENT_CLI VARCHAR2(20),
    COD_SERVICIO NUMBER,
    COD_SUCURSAL NUMBER,
    COD_VEHICULO NUMBER
  );
  ALTER TABLE FACTURA ADD CONSTRAINT PK_NUM_FACTURA PRIMARY KEY (NUM_FACTURA);      
  ALTER TABLE FACTURA ADD CONSTRAINT FK_NUM_IDENT_CLI FOREIGN KEY(NUM_IDENT_CLI) REFERENCES CLIENTE (NUM_IDENT_CLI);
  ALTER TABLE FACTURA ADD CONSTRAINT FK_COD_SERVICIO FOREIGN KEY(COD_SERVICIO) REFERENCES DESCRIPCION_SERVICIO (COD_SERVICIO);
  ALTER TABLE FACTURA ADD CONSTRAINT FK_COD_SUCURSAL FOREIGN KEY(COD_SUCURSAL) REFERENCES ALMACEN (COD_SUCURSAL);
  ALTER TABLE FACTURA ADD CONSTRAINT FK_COD_VEHICULO FOREIGN KEY(COD_VEHICULO) REFERENCES VEHICULO (COD_VEHICULO);
  CREATE SEQUENCE SEQ_FACTURA MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;