CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_CANT_PROD 
 AFTER INSERT ON DETALLE_PRODUCTO FOR EACH ROW
  
  DECLARE
   BEGIN
     UPDATE PRODUCTO SET CANTIDAD_PROD = CANTIDAD_PROD - :NEW.CAN_PRODUCTO_VENDIDO
                   WHERE COD_PRODUCTO = :NEW.COD_PRODUCTO;
   END; 
/